"""Registration workflow primitives shared by the Web registration engine."""

from .state import (
    EMAIL_REQUEST_MIN_INTERVAL,
    DuplicateSSOError,
    ExistingAccountError,
    RegistrationState,
    VerificationRequestError,
    email_request_slot,
    is_xai_permission_denied,
    submit_is_in_flight,
)
from .profile import (
    ProfileSubmitSnapshot,
    ProfileSubmitStage,
    classify_profile_submit,
    save_profile_diagnostics,
)
from .signup import (
    SignupEnvironmentError,
    SignupPageSnapshot,
    SignupPageStage,
    classify_signup_page,
    save_signup_diagnostics,
)
from .backend import (
    ProtocolEnvironmentError,
    ProtocolRegistrationBackend,
    SignupParameterDiscovery,
    SignupParameters,
    apply_sso_cookies,
    build_protocol_session,
    build_registration_backend,
    build_signup_payload,
    expand_set_cookie_chain,
    follow_sso_http,
    redact_sensitive_text,
    resolve_protocol_proxy,
)
from .turnstile import (
    BrowserTurnstileProvider,
    ExternalTurnstileProvider,
    TurnstileSolveError,
    parse_proxy_for_yescaptcha,
    resolve_turnstile_settings,
)

__all__ = [
    'EMAIL_REQUEST_MIN_INTERVAL',
    'DuplicateSSOError',
    'ExistingAccountError',
    'RegistrationState',
    'VerificationRequestError',
    'email_request_slot',
    'is_xai_permission_denied',
    'submit_is_in_flight',
    'ProfileSubmitSnapshot',
    'ProfileSubmitStage',
    'classify_profile_submit',
    'save_profile_diagnostics',
    'SignupEnvironmentError',
    'SignupPageSnapshot',
    'SignupPageStage',
    'classify_signup_page',
    'save_signup_diagnostics',
    'ProtocolEnvironmentError',
    'ProtocolRegistrationBackend',
    'SignupParameterDiscovery',
    'SignupParameters',
    'apply_sso_cookies',
    'build_protocol_session',
    'build_registration_backend',
    'build_signup_payload',
    'expand_set_cookie_chain',
    'follow_sso_http',
    'redact_sensitive_text',
    'resolve_protocol_proxy',
    'BrowserTurnstileProvider',
    'ExternalTurnstileProvider',
    'TurnstileSolveError',
    'parse_proxy_for_yescaptcha',
    'resolve_turnstile_settings',
]
